
name: "PR Conflicts checker"
on:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check-pr-conflict:
    if: github.repository_owner == 'vyos'
    uses: vyos/.github/.github/workflows/check-pr-merge-conflict.yml@current
    secrets: inherit
