name: PR Mirror and Repo Sync

on:
  pull_request_target:
    types: [closed]
    branches: [current]
  workflow_dispatch:
    inputs:
      sync_branch:
        description: 'Branch to mirror'
        required: true
        default: 'current'
        type: choice
        options:
          - current

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  call-pr-mirror-repo-sync:
    if: |
      github.repository_owner == 'vyos' &&
      (
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
      )
    uses: vyos/.github/.github/workflows/pr-mirror-repo-sync.yml@current
    with:
      sync_branch: ${{ github.event.inputs.sync_branch || 'current' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
